server:
  port: 8089

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: kernel-authority
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/warlock?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
      filters: stat
      # 配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      # 一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20

  redis:
    host: localhost
    database: 0
    port: 6379
    lettuce:
      shutdown-timeout: 300ms

dubbo:
  application:
    name: kernel-admin
  protocol:
    name: dubbo
    port: 20883
  registry:
    address: zookeeper://127.0.0.1:2181
    check: false
    group: warlock
  scan:
    base-packages: com.learn.kernel.*.service
