server:
  port: 8090

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: kernel-search
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
    timeout: 200
  protocol:
    name: dubbo
    port: 20884
  scan:
    base-packages: com.learn.kernel.search.service